### ISSUE TITLE
template loading error

### ISSUE THREAD

**Issue by pranav095** [projectdiscovery/nuclei-templates#455] opened 2020-09-14 05:57 UTC
Hello, I am facing an 
![nucleiCveError](https://user-images.githubusercontent.com/32648862/93048772-41974900-f67d-11ea-8095-a4d0bcb5cdd6.PNG)
error while using the cve template. All other templates are running but I am not able to figure out why the cve template is not running 
![Uploading nucleiOtherTemp.PNG…]()

**Comment by pranav095** [comment] 2020-09-14 06:06
![nucleiOtherTemp](https://user-images.githubusercontent.com/32648862/93049378-8079ce80-f67e-11ea-82c5-900685860470.PNG)

**Comment by bauthard** [comment] 2020-09-16 08:05
Hey @pranav095, 

Can you share the output of `nuclei -t cves/ -l your_list.txt -v`

**Comment by pranav095** [comment] 2020-09-16 12:13
Yeah sure. Here it is

[image: image.png]

Thank you
Pranav

**Comment by pranav095** [comment] 2020-09-16 12:45
![image](https://user-images.githubusercontent.com/32648862/93338879-87ecd380-f848-11ea-8380-8c9d0ac8be9e.png)

**Comment by CasperGN** [comment] 2020-09-17 07:19
Im not able to reproduce also running v.2.1.1 and `nuclei -update-templates`.
Is this perhaps specific on Windows?

**Comment by pranav095** [comment] 2020-09-17 07:27
Hello, I am attaching a video POC
https://drive.google.com/file/d/1ayrv78QQuKMMDPy1sG2jztxKzpbwYtT2/view?usp=sharing

**Comment by pranav095** [comment] 2020-09-21 09:47
Hello any updates?

**Comment by CasperGN** [comment] 2020-09-21 09:50
As noted above, i cannot replicate on MacOS nor Fedora. I'm not clicking the above link for POC video.
I haven't got a Windows machine to test on at the moment, and as such can't give much assistance I'm affraid.

/ Casper

**Comment by pranav095** [comment] 2020-09-21 09:52
So can you pass it to someone who might be using the windows machine? I am not able to utilize the template properly. CVES is the main part

**Comment by CasperGN** [comment] 2020-09-21 10:01
I've asked on Discord.
Could you, just for the sake of it, do the following:

```
> GO111MODULE=on go get -u -v github.com/projectdiscovery/nuclei/v2/cmd/nuclei
> nuclei -update-templates
```
Just to make sure you have clean and updated?

/ Casper

**Comment by pranav095** [comment] 2020-10-08 11:38
Hello, still not working
Except Cves, every other template is working

**Comment by pranav095** [comment] 2020-10-08 11:38
Can someone anydesk and help me out? or check the issue?

**Comment by ehsandeep** [comment] 2021-02-18 15:39
Hi @pranav095, there is a new release since this issue was created, can you confirm if you still able to reproduce this with `nuclei 2.2.0`

**Comment by ehsandeep** [comment] 2021-02-20 14:25
Closing as unable to reproduce this, if you still facing issue with this, DM us on the discord server.

**Closed by ehsandeep** 2021-02-20 14:25 UTC
Labels: Type: Question
