### ISSUE TITLE
nuclei-templates all error?

### ISSUE THREAD

**Issue by ltfafei** [projectdiscovery/nuclei-templates#7226] opened 2023-05-12 06:46 UTC
I found that the previous version of POC was in the thrust-templates directory, but now it is in the thrust-templates /http directory, but running all results in errors

 
![image](https://github.com/projectdiscovery/nuclei-templates/assets/43526141/f0f4c212-9a70-4e71-b4f3-88009fa55140)

![image](https://github.com/projectdiscovery/nuclei-templates/assets/43526141/9e39218e-2cac-4d7c-94d4-f814f3eec2b4)

![image](https://github.com/projectdiscovery/nuclei-templates/assets/43526141/e79ee9ee-3ba2-4101-a769-56839a7dee1c)

**Comment by DhiyaneshGeek** [comment] 2023-05-12 06:47
@ltfafei It seems your nuclei version is outdated 

Kindly update to the latest version

`nuclei -update`

Thanks

**Comment by ltfafei** [comment] 2023-05-12 06:53
yes, now update, but error protocol syntax

![image](https://github.com/projectdiscovery/nuclei-templates/assets/43526141/c108a591-7db3-4ed1-bb19-9e39e5ab3667)

**Comment by ltfafei** [comment] 2023-05-12 07:10
OK, i got it

**Comment by DhiyaneshGeek** [comment] 2023-05-12 09:19
Hope the issue is resolved i'm closing the issue now 

Thanks !

**Closed by DhiyaneshGeek** 2023-05-12 09:19 UTC
Labels: Type: Bug
