### ISSUE TITLE
Template not working as expected

### ISSUE THREAD

**Issue by Vishnuraghav89** [projectdiscovery/nuclei-templates#2521] opened 2021-08-30 17:09 UTC
Hi Sandeep and Team,

I have created below template but unfortunately it is not working as expected.

**Template that I have created**

```javascript
id: php setup exposed

info:
  name: php setup exposed
  author: vishnu
  severity: medium

requests:
  - raw:
      - |
        GET /{{setup}} HTTP/1.1
        Host: {{Hostname}}

    payloads:
       setup: helpers/payloads/php-setup.txt
    attack: sniper

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "phpMyAdmin"
          - "Export"
          - "Overview"
          - "Import"
        part: header
        condition: and
```

**Template that is already there....**
```javascript
id: phpmyadmin-setup

info:
  name: Publicly Accessible Phpmyadmin Setup
  author: sheikhrishad
  severity: medium
  tags: misc

requests:
  - method: GET
    path:
      - "{{BaseURL}}/phpmyadmin/scripts/setup.php"
      - "{{BaseURL}}/_phpmyadmin/scripts/setup.php"
      - "{{BaseURL}}/forum/phpmyadmin/scripts/setup.php"
      - "{{BaseURL}}/php/phpmyadmin/scripts/setup.php"
      - "{{BaseURL}}/typo3/phpmyadmin/scripts/setup.php"
      - "{{BaseURL}}/web/phpmyadmin/scripts/setup.php"
      - "{{BaseURL}}/xampp/phpmyadmin/scripts/setup.php"
      - "{{BaseURL}}/sysadmin/phpMyAdmin/scripts/setup.php"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "You want to configure phpMyAdmin using web interface"

      - type: status
        status:
          - 200
```

This one working as expected but mine is not working ....could you please check and le us know what I'm missing here.

This is how my php-setup.txt looks like
```
phpmyadmin/setup/
_phpmyadmin/setup/
forum/phpmyadmin/setup/
php/phpmyadmin/setup/
typo3/phpmyadmin/setup/
web/phpmyadmin/setup/
xampp/phpmyadmin/setup/
sysadmin/phpMyAdmin/setup/
```

Thanks and regards,
Vishnu Raghav

**Comment by princechaddha** [comment] 2021-08-31 08:27
Hello @Vishnuraghav89, The above template works as expected. Please confirm the payload's file path before running the template and it would be helpful if you can provide `-debug` data so we can further investigate the issue

**Comment by ehsandeep** [comment] 2021-09-01 07:21
Moving this to the discussion as this is not a bug but a syntax issue.

**Closed** 2021-09-01 07:21 UTC
