### ISSUE TITLE
Error execute code protocol templates

### ISSUE THREAD

**Issue by mikemicky4321** [projectdiscovery/nuclei-templates#8711] opened 2023-11-28 04:12 UTC
### Nuclei Version:
I am using 3+ version

### Template file:
https://github.com/projectdiscovery/nuclei/blob/main/integration_tests/protocols/code/py-file.yaml
id: py-file

info:
  name: py-file
  author: pdteam
  severity: info
  tags: code
  description: |
    py-file

code:
  - engine:
      - py
      - python3
    source: protocols/code/pyfile.py
    
    matchers:
      - type: word
        words:
          - "hello from input"

### Command to reproduce:
./nuclei -t py-file.yaml

### Anything else:
Tried with all the versions of nuclei and still getting the error "[FTL] Could not run nuclei: no templates provided for scan"
![image](https://github.com/projectdiscovery/nuclei-templates/assets/115986628/b1a817f0-542d-4f5f-861b-f9ecc0d94cb9)
Nuclei could validate the template but it cannot executing it.
![image](https://github.com/projectdiscovery/nuclei-templates/assets/115986628/c799c161-c733-4ee1-a981-8826c8538c0c)

https://github.com/projectdiscovery/nuclei/blob/main/integration_tests/protocols/code/py-file.yaml

**Comment by pussycat0x** [comment] 2023-11-28 07:44
Hello, @mikemicky4321, please endorse the template by utilizing the argument `-sign`. Additionally, incorporate `self-contained: true` in the template.
Note: you can employ the self-contained field. If you provide a file name as a URL, it will be included as standard input.

```
id: py-file

info:
  name: py-file
  author: pdteam
  severity: info
  tags: code
  description: |
    py-file

self-contained: true
code:
  - engine:
      - py
      - python3
    source: /tmp/pyfile.py
    
    matchers:
      - type: word
        words:
          - "hello"
# digest: 4b0a00483046022100d9c6a99f669150daa40e9be3495186c9946c6b2f8172424a27c9dae233197b01022100d74ebe05d16ba8d23d0d63e621572b92e2f29cb85da08a37c956a1446ba54a85:c8251d2f4b494560fa261588bedfe7b7
```

**Comment by mikemicky4321** [comment] 2023-11-28 12:45
Hello @pussycat0x ,
Thanks for your quick response. Could you please help me with this? I am getting below error when trying to execute your template.
![image](https://github.com/projectdiscovery/nuclei-templates/assets/115986628/7fbe21fc-74b3-4deb-ba56-e6a2c4cb66e8)

**Comment by pussycat0x** [comment] 2023-11-28 17:45
Hi @mikemicky4321  you have to use `-lfa` option to refer any payloads/code outside of nuclei templates directory

**Comment by DhiyaneshGeek** [comment] 2023-11-29 13:27
Hi @mikemicky4321 

Hope the issue is fixed 

Are you on our Discord channel? If not, you can join our [Discord server](https://discord.com/invite/projectdiscovery).

Thanks 😄

**Closed by DhiyaneshGeek** 2023-11-29 13:27 UTC
Labels: Type: Bug, Done
